// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    sql.NullString
	Url       sql.NullString
}

type FeedsFollow struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	FeedID    string
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ApiKey    string
}
